### ISSUE TITLE
Improve structure

### ISSUE THREAD

**Issue by gabrielsiedler** [full-stack-hardcore/teamup-server#1]
- We know it is a server. So rename the `server` folder to `src`;
- It doesnt have angular. Remove the entry `"ng": "ng",`;
- Parser (and other server definitions) should be added to a more generic file:
```
router.use(bodyParser.json());
router.use(bodyParser.urlencoded({
  extended: true
}));
```
This kind of configuration should be for all routes;
- All routes should have `api/` prefix. For example: `http://localhost:3000/api/route`;
- We only have API routes so far. Remove `routes` directory. Move the `api` folder to `/src`;
- Remove the `build` directory. `ts-node` handle compiled code under the hood, so it has good performance and can be used in production.
_also add a watch to your project:_ 

```
"start": "ts-node src/server.ts",
"watch": "ts-node-dev --poll --no-notify src/app.ts",
```

**Comment by lucasnachtigall** [comment]
Fixes pushed
